final filesJson = [
  "webgl_camera",
  "webgl_camera_array",
  "webgl_shadow_contact",
  "webgl_geometry_text",
  "webgl_geometry_shapes",
  "webgl_geometry_extrude_shapes",
  "webgl_geometry_dynamic",
  "webgl_geometry_extrude_splines",
  "webgl_materials_browser",
  "webgl_instancing_performance",
  "webgl_instancing_raycast",
  "webgl_instancing_dynamic",
  "webgl_interactive_voxelpainter",
  "webgl_gpgpu_protoplanet",
  "webgl_shadowmap_viewer",
  "webgl_shadowmap_pointlight",
  "webgl_loader_texture_basis",
  "webgl_loader_svg",
  "webgl_loader_gltf",
  "webgl_loader_fbx",
  // "webgl_loader_gltf_test",
  "webgl_loader_obj",
  "webgl_loader_obj_mtl",
  "webgl_loader_gcode",
  'webgl_loader_xyz',
  "webgl_animation_keyframes",
  "webgl_skinning_simple",
  "webgl_animation_multiple",
  "webgl_animation_cloth",
  "misc_animation_keys",
  "webgl_animation_skinning_ik",
  "webgl_clipping_advanced",
  "webgl_clipping_intersection",
  "webgl_clipping_stencil",
  "webgl_clipping",
  "webgl_geometries",
  "webgl_materials",
  "webgl_animation_skinning_blending",
  "webgl_animation_skinning_additive_blending",
  "webgl_animation_skinning_morph",
  "webgl_geometry_colors",
  "webgl_lensflares",
  "webgl_lights_rectarealight",
  "webgl_postprocessing_sobel",
  "webgl_water",
  //"webgl_geometry_csg",
  "webgl_helpers",
  "webgl_morphtargets",
  "webgl_morphtargets_sphere",
  "webgl_morphtargets_horse",
  'webgl_morphtargets_face',
  "misc_controls_orbit",
  "misc_controls_trackball",
  "misc_controls_arcball",
  "misc_controls_map",
  "misc_controls_pointerlock",
  'misc_controls_fly',
  "multi_views",
  // 'basic_physics',
  // 'collision_physics',
  // 'compound_physics',
  // 'compound2_physics',
  // 'moving_physics',
  'games_fps',
  'marching_cubes',
  'misc_controls_transform',
  'webgl_volume_perlin',
  'webgl_volume_cloud',
  'webgl_ubo_arrays'
];
