name: three_js_modifers
description: "three_js modifer package converted from threejs and three_dart package."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_core:
    path: ../three_js_core
  three_js_math: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0