name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  three_js_core_loaders: ^0.2.0
  three_js_core: ^0.2.0
  three_js_controls: ^0.2.0
  three_js_helpers: ^0.2.0
  three_js_math: ^0.2.0
  three_js_advanced_loaders:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  three_js_helpers:
    path: ../../three_js_helpers

flutter:
  uses-material-design: true
  assets:
    - assets/Parrot.gltf
    - assets/Soldier.gltf