name: three_js_xr
description: "Flutter three_js_xr package converted from threejs to support webxr, arkit and arcore."
version: 0.0.1
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_xr

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_math: ^0.1.0
  three_js_core: #^0.1.0
    path: ../three_js_core
  web: ^1.1.1
  js: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
