name: three_js_math
description: "Flutter threejs math package converted from threejs and three_dart package."
version: 0.0.1
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_math

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  flutter_angle: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
