name: three_js_simple_loaders
description: "three_js simple loader package e.g.(obj and stl) converted from threejs and three_dart package."
version: 0.0.1
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_simple_loaders

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_core_loaders:
    path: ../three_js_core_loaders
  three_js_core:
    path: ../three_js_core
  three_js_math:
    path: ../three_js_math
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
