name: three_cad
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  three_js: ^0.1.2
  three_js_helpers: ^0.1.0
  three_js_line: ^0.1.0
  three_js_bvh_csg: ^0.1.0
  three_js_exporters: ^0.1.0
  three_js_transform_controls: ^0.1.0
  css:
    git:
      url: https://github.com/Knightro63/css.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


dependency_overrides:
  permission_handler_apple:
    git:
      url: https://github.com/alex-melnyk/flutter-permission-handler.git 
      path: permission_handler_apple

flutter:
  uses-material-design: true
  assets:
    - assets/draw/line.svg