name: three_cad
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  three_js: ^0.0.5
  three_js_helpers: ^0.0.4
  three_js_line: ^0.0.1
  three_js_bvh_csg: ^0.0.1
  three_js_exporters: ^0.0.2
  three_js_geometry: ^0.0.2
  three_js_transform_controls: ^0.0.3
  css:
    git:
      url: https://github.com/Knightro63/css.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


dependency_overrides:
  permission_handler_apple:
    git:
      url: https://github.com/alex-melnyk/flutter-permission-handler.git 
      path: permission_handler_apple
  three_js_core:
    path: ../packages/three_js_core
  three_js_core_loaders:
    path: ../packages/three_js_core_loaders
  three_js_math:
    path: ../packages/three_js_math
  three_js_modifers:
    path: ../packages/three_js_modifers
  three_js_bvh_csg:
    path: ../packages/three_js_bvh_csg
  three_js_objects:
    path: ../packages/three_js_objects
  three_js_transform_controls:
    path: ../packages/three_js_transform_controls
  three_js_controls:
    path: ../packages/three_js_controls
  three_js_helpers:
    path: ../packages/three_js_helpers
  flutter_angle:
    path: ../../flutter_angle/flutter_angle
  flutter_angle_darwin:
    path: ../../flutter_angle/flutter_angle_darwin

flutter:
  uses-material-design: true
  assets:
    - assets/draw/line.svg