name: three_js_video_texture
description: "A three_js package that helps with video textures."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_core: ^0.2.0
  three_js_math: ^0.2.0
  media_kit: ^1.2.0
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter: