name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_gl: ^0.0.21
  three_js_objects:
    path: ../
  three_js_core:
    path: ../../three_js_core
  three_js_math:
    path: ../../three_js_math
  three_js_controls:
    path: ../../three_js_controls

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
