name: three_js_svg
description: "Flutter three_js_svg is a viewer, loader, and exporter package converted from threejs and three_dart package."
version: 0.0.2
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_svg

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
  three_js_curves: ^0.0.1
  three_js_core_loaders: ^0.0.2
  three_js_core: ^0.0.1
  three_js_math: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0