name: three_js
description: "Flutter package converted from threejs and three_dart to allow users to view, edit and control 3D models."
version: 0.0.1
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_math:
    path: ../three_js_math
  three_js_advanced_loaders:
    path: ../three_js_advanced_loaders
  three_js_animations:
    path: ../three_js_animations
  three_js_controls:
    path: ../three_js_controls
  three_js_core:
    path: ../three_js_core
  three_js_core_loaders:
    path: ../three_js_core_loaders
  three_js_curves:
    path: ../three_js_curves
  three_js_simple_loaders:
    path: ../three_js_simple_loaders
  three_js_text:
    path: ../three_js_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
