name: three_js
description: "Flutter package converted from threejs and three_dart to allow users to view, edit, and control 3D models."
version: 0.2.6
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js

topics:
  - threejs
  - games
  - animations
  - flutter3d
  - model3d

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_math: ^0.2.5
  three_js_advanced_loaders: ^0.2.4
  three_js_animations: ^0.2.1
  three_js_controls: ^0.2.1
  three_js_core: ^0.2.6
  three_js_core_loaders: ^0.2.1
  three_js_curves: ^0.2.0
  three_js_simple_loaders: ^0.2.2
  three_js_text: ^0.2.0
  three_js_geometry: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux: